# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  js:
    name: JS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js/var-7

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: cd 
    - run: npm i
    # - run: npm run build --if-present
    - run: npm test
  
  react:
    name: React
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react/var-1/main

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: cd 
    - run: npm i
    # - run: npm run build --if-present
    - run: npm test
  

  simple:

    name: Simple
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simple/var-3/main

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: cd 
    - run: npm i
    # - run: npm run build --if-present
    - run: npm test


  
  rest:
    name: Rest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rest/var-4/main

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: cd 
    - run: npm i
    # - run: npm run build --if-present
    - run: npm test




